services:
  api:
    build: .
    volumes:
      - ./data:/app/data  # Persist the data directory
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017  # MongoDB connection string
    ports:
      - "5000:5000"  # Expose the API on port 5000

  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - mongo_data:/data/db  # Persist MongoDB data
    ports:
      - "27017:27017"  # Expose MongoDB for Grafana to connect

  pyspark:
    image: apache/spark-py
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data  # Mount data directory
    depends_on:
      - mongo
    command: >
      bash -c "sleep 10 &&
      curl http://api:5000/download_last_n_months/despesas-execucao/3 &&
      curl http://api:5000/download_last_n_months/notas-fiscais/3 &&
      curl http://api:5000/download_last_n_months/emendas-parlamentares/3 &&
      python /app/pyspark/load_to_mongodb.py &&
      mongo --host mongo /app/elt_mongodb/script1.js &&
      mongo --host mongo /app/elt_mongodb/script2.js"

volumes:
  mongo_data:
